projects:
  aiWebtoolsUe4GraphqlAPI:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: mhj6jnw2nvfj7c4ex3bxewyxfm
      endpoints:
        prod: >-
          https://wa2l62j23na3njui6b72pv3tl4.appsync-api.us-east-1.amazonaws.com/graphql
